### ISSUE TITLE
Can't resolve ng2-cable

### ISSUE THREAD

**Issue by Valindo** [viktor-shmigol/ng2-cable#1]
I have installed the packages as prescribed.
After I include it in my app.component.ts, it breaks, here is the error

`ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'ng2-cable' in '/Users/valindogodinho/Projects/ANGULARTCP/src/app'
 @ ./src/app/app.component.ts 11:0-50
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main`

help please.

**Comment by viktor-shmigol** [comment]
Hi @Valindo . Could you please provide me more information about your problem: node version, angular version or send me link to your repository. Thank you for letting me know about this situation.

**Comment by viktor-shmigol** [comment]
@Valindo Try to import this plugin like this: import { Ng2Cable, Broadcaster } from 'ng2-cable/js/index';

**Comment by Valindo** [comment]
Hey, Sorry for the late reply.
The import statement worked! Thank you so much, you're a life saver :D
