### ISSUE TITLE
Ionic 3 build Problem

### ISSUE THREAD

**Issue by DevillBuster** [viktor-shmigol/ng2-cable#12]
Every thing work fine with Ionic serve but when i try to make build for android in ionic. it shows error and i get a blank application error is Uncaught SyntaxError: Use of const in strict mode.

This occur moment i add plugin the application. And this is error is gone the moment i remove this plugin from my application.
Can you please look into this problem

node version 8.0.0
npm version 5.0.0

**Comment by viktor-shmigol** [comment]
@DevillBuster thanks for letting me know about that. Could you please provide me link to your repository.I'll try to help you

**Comment by DevillBuster** [comment]
@viktor-shmigol  i tried to make build of your repository i which you uses this module as example and get the same error as demonstrated above.

**Comment by viktor-shmigol** [comment]
@DevillBuster I have fixed it. You can try it now. Note: I have updated readme, so could you please take a look at it. If you have a questions just let me know. Also I've updated ionic3 example: https://github.com/viktor-shmigol/ng2-cable-ionic2-example
