### ISSUE TITLE
Error installing ng2-cable

### ISSUE THREAD

**Issue by hazardco** [viktor-shmigol/ng2-cable#15]
I am trying to use ng2-cable with a Rails application. I have the following error when installing it:

npm install ng2-cable --save
eventos@0.0.1 /Users/luis/Sites/ionic3/eventos
├── UNMET PEER DEPENDENCY @angular/core@4.4.3
├── ng2-cable@2.0.7 
└── UNMET PEER DEPENDENCY zone.js@0.8.18

Maybe it's silly but I'm a rookie in Angular.

My package.json:

Thanks and sorry for my english.

**Comment by hazardco** [comment]
it´s ok!!!

import { Ng2Cable, Broadcaster } from 'ng2-cable/index';

**Comment by viktor-shmigol** [comment]
cool
