### ISSUE TITLE
Can't resolve 'actioncable'

### ISSUE THREAD

**Issue by cesar-tonnoir** [viktor-shmigol/ng2-cable#4]
Hi!
I'm trying to include Ng2Cable to my Angular2 application using angular-cli, and receive this error:

```
ERROR in ./~/ng2-cable/js/ng2-cable.js
Module not found: Error: Can't resolve 'actioncable' in '/home/cesar/perso/mike-angular/node_modules/ng2-cable/js'
```

In my `app.module.ts`:
```typescript
import { Ng2Cable, Broadcaster } from 'ng2-cable/js/index';

@NgModule({
  ...
  providers: [
    ...
    Ng2Cable,
    Broadcaster
  ]
})
```

Has anyone faced this problem before?
Thanks.

**Comment by viktor-shmigol** [comment]
@cesar-tonnoir  hey thanks for letting me know about that. It's very strange situation, because I have same project with angular cli and everything is working well. So could you please send me link to your repo and I'll try to help you.

**Comment by cesar-tonnoir** [comment]
That's a private one, I'll try to get you an access and keep looking for a solution in the meantime. Thanks for the help anyway!

**Comment by BenjaminKim** [comment]
same here.
