### ISSUE TITLE
Error on Angular 4

### ISSUE THREAD

**Issue by ebosantos** [viktor-shmigol/ng2-cable#6]
When I ran 'npm install', the following error was shown:

> UNMET PEER DEPENDENCY @angular/core@2.4.10

And this is generating new issues.

**Comment by ebosantos** [comment]
@viktor-shmigol What do you suggest me? Are you planning a new version in compliance with Angular 4?

**Comment by viktor-shmigol** [comment]
@ebosantos Sorry for long delay. I have added support for angular 4. Thanks for letting me know about that

**Comment by ebosantos** [comment]
Awesome @viktor-shmigol . Thanks very much!
